// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client.types

import com.boundaryml.baml.*


data class CookingConstraints(
    
    val goalSummary: String,
    val diet: String,
    val maxCookTimeMinutes: Long,
    val proteinPriority: String,
    val preferredCuisines: List<String>,
    val avoidIngredients: List<String>
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("CookingConstraints", mapOf(
            "goalSummary" to goalSummary,"diet" to diet,"maxCookTimeMinutes" to maxCookTimeMinutes,"proteinPriority" to proteinPriority,"preferredCuisines" to preferredCuisines,"avoidIngredients" to avoidIngredients
        ))
    }

    override fun bamlTypeName(): String = "CookingConstraints"

    companion object : BamlDeserializable<CookingConstraints> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): CookingConstraints {
            return CookingConstraints(
                goalSummary = Serde.coerceString(Serde.requireField(fields, "goalSummary")),diet = Serde.coerceString(Serde.requireField(fields, "diet")),maxCookTimeMinutes = Serde.coerceLong(Serde.requireField(fields, "maxCookTimeMinutes")),proteinPriority = Serde.coerceString(Serde.requireField(fields, "proteinPriority")),preferredCuisines = Serde.coerceList(Serde.requireField(fields, "preferredCuisines")) { item -> Serde.coerceString(item) },avoidIngredients = Serde.coerceList(Serde.requireField(fields, "avoidIngredients")) { item -> Serde.coerceString(item) }
            )
        }
    }
}

data class IngredientDetection(
    
    val name: String,
    val quantity: String?,
    val confidence: Double,
    val note: String?
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("IngredientDetection", mapOf(
            "name" to name,"quantity" to quantity,"confidence" to confidence,"note" to note
        ))
    }

    override fun bamlTypeName(): String = "IngredientDetection"

    companion object : BamlDeserializable<IngredientDetection> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): IngredientDetection {
            return IngredientDetection(
                name = Serde.coerceString(Serde.requireField(fields, "name")),quantity = Serde.coerceNullable(fields["quantity"]) { value -> Serde.coerceString(value) },confidence = Serde.coerceDouble(Serde.requireField(fields, "confidence")),note = Serde.coerceNullable(fields["note"]) { value -> Serde.coerceString(value) }
            )
        }
    }
}

data class InventoryAnalysis(
    
    val title: String,
    val summary: String,
    val ingredients: List<IngredientDetection>,
    val possibleIngredients: List<String>
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("InventoryAnalysis", mapOf(
            "title" to title,"summary" to summary,"ingredients" to ingredients,"possibleIngredients" to possibleIngredients
        ))
    }

    override fun bamlTypeName(): String = "InventoryAnalysis"

    companion object : BamlDeserializable<InventoryAnalysis> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): InventoryAnalysis {
            return InventoryAnalysis(
                title = Serde.coerceString(Serde.requireField(fields, "title")),summary = Serde.coerceString(Serde.requireField(fields, "summary")),ingredients = Serde.coerceList(Serde.requireField(fields, "ingredients")) { item -> Serde.coerceNamedType<IngredientDetection>(item, typeMap, "TYPES", "IngredientDetection") },possibleIngredients = Serde.coerceList(Serde.requireField(fields, "possibleIngredients")) { item -> Serde.coerceString(item) }
            )
        }
    }
}

data class RecipePlan(
    
    val title: String,
    val whyItFits: String,
    val recipes: List<RecipeSuggestion>
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("RecipePlan", mapOf(
            "title" to title,"whyItFits" to whyItFits,"recipes" to recipes
        ))
    }

    override fun bamlTypeName(): String = "RecipePlan"

    companion object : BamlDeserializable<RecipePlan> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): RecipePlan {
            return RecipePlan(
                title = Serde.coerceString(Serde.requireField(fields, "title")),whyItFits = Serde.coerceString(Serde.requireField(fields, "whyItFits")),recipes = Serde.coerceList(Serde.requireField(fields, "recipes")) { item -> Serde.coerceNamedType<RecipeSuggestion>(item, typeMap, "TYPES", "RecipeSuggestion") }
            )
        }
    }
}

data class RecipeSuggestion(
    
    val name: String,
    val description: String,
    val cookTimeMinutes: Long,
    val proteinEstimateGrams: Long,
    val difficulty: String,
    val usesIngredients: List<String>,
    val missingIngredients: List<String>,
    val steps: List<String>
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("RecipeSuggestion", mapOf(
            "name" to name,"description" to description,"cookTimeMinutes" to cookTimeMinutes,"proteinEstimateGrams" to proteinEstimateGrams,"difficulty" to difficulty,"usesIngredients" to usesIngredients,"missingIngredients" to missingIngredients,"steps" to steps
        ))
    }

    override fun bamlTypeName(): String = "RecipeSuggestion"

    companion object : BamlDeserializable<RecipeSuggestion> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): RecipeSuggestion {
            return RecipeSuggestion(
                name = Serde.coerceString(Serde.requireField(fields, "name")),description = Serde.coerceString(Serde.requireField(fields, "description")),cookTimeMinutes = Serde.coerceLong(Serde.requireField(fields, "cookTimeMinutes")),proteinEstimateGrams = Serde.coerceLong(Serde.requireField(fields, "proteinEstimateGrams")),difficulty = Serde.coerceString(Serde.requireField(fields, "difficulty")),usesIngredients = Serde.coerceList(Serde.requireField(fields, "usesIngredients")) { item -> Serde.coerceString(item) },missingIngredients = Serde.coerceList(Serde.requireField(fields, "missingIngredients")) { item -> Serde.coerceString(item) },steps = Serde.coerceList(Serde.requireField(fields, "steps")) { item -> Serde.coerceString(item) }
            )
        }
    }
}

data class ShoppingItem(
    
    val name: String,
    val quantity: String,
    val reason: String,
    val estimatedCostUsd: Double
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("ShoppingItem", mapOf(
            "name" to name,"quantity" to quantity,"reason" to reason,"estimatedCostUsd" to estimatedCostUsd
        ))
    }

    override fun bamlTypeName(): String = "ShoppingItem"

    companion object : BamlDeserializable<ShoppingItem> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): ShoppingItem {
            return ShoppingItem(
                name = Serde.coerceString(Serde.requireField(fields, "name")),quantity = Serde.coerceString(Serde.requireField(fields, "quantity")),reason = Serde.coerceString(Serde.requireField(fields, "reason")),estimatedCostUsd = Serde.coerceDouble(Serde.requireField(fields, "estimatedCostUsd"))
            )
        }
    }
}

data class ShoppingPlan(
    
    val title: String,
    val items: List<ShoppingItem>,
    val pantryWins: List<String>,
    val notes: List<String>,
    val estimatedTotalCostUsd: Double
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("ShoppingPlan", mapOf(
            "title" to title,"items" to items,"pantryWins" to pantryWins,"notes" to notes,"estimatedTotalCostUsd" to estimatedTotalCostUsd
        ))
    }

    override fun bamlTypeName(): String = "ShoppingPlan"

    companion object : BamlDeserializable<ShoppingPlan> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): ShoppingPlan {
            return ShoppingPlan(
                title = Serde.coerceString(Serde.requireField(fields, "title")),items = Serde.coerceList(Serde.requireField(fields, "items")) { item -> Serde.coerceNamedType<ShoppingItem>(item, typeMap, "TYPES", "ShoppingItem") },pantryWins = Serde.coerceList(Serde.requireField(fields, "pantryWins")) { item -> Serde.coerceString(item) },notes = Serde.coerceList(Serde.requireField(fields, "notes")) { item -> Serde.coerceString(item) },estimatedTotalCostUsd = Serde.coerceDouble(Serde.requireField(fields, "estimatedTotalCostUsd"))
            )
        }
    }
}

data class ShoppingPlanDeck(
    
    val title: String,
    val plans: List<ShoppingPlanOption>
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("ShoppingPlanDeck", mapOf(
            "title" to title,"plans" to plans
        ))
    }

    override fun bamlTypeName(): String = "ShoppingPlanDeck"

    companion object : BamlDeserializable<ShoppingPlanDeck> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): ShoppingPlanDeck {
            return ShoppingPlanDeck(
                title = Serde.coerceString(Serde.requireField(fields, "title")),plans = Serde.coerceList(Serde.requireField(fields, "plans")) { item -> Serde.coerceNamedType<ShoppingPlanOption>(item, typeMap, "TYPES", "ShoppingPlanOption") }
            )
        }
    }
}

data class ShoppingPlanOption(
    
    val recipeName: String,
    val plan: ShoppingPlan
    
) : BamlSerializable {

    override fun encode(): com.boundaryml.baml.cffi.HostValue {
        return Serde.encodeClass("ShoppingPlanOption", mapOf(
            "recipeName" to recipeName,"plan" to plan
        ))
    }

    override fun bamlTypeName(): String = "ShoppingPlanOption"

    companion object : BamlDeserializable<ShoppingPlanOption> {
        override fun decode(fields: Map<String, Any?>, typeMap: BamlTypeMap): ShoppingPlanOption {
            return ShoppingPlanOption(
                recipeName = Serde.coerceString(Serde.requireField(fields, "recipeName")),plan = Serde.coerceNamedType<ShoppingPlan>(Serde.requireField(fields, "plan"), typeMap, "TYPES", "ShoppingPlan")
            )
        }
    }
}
