// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client.types

import com.boundaryml.baml.*

