// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client

import com.boundaryml.baml.*
import kotlin.reflect.KClass

fun registerBamlTypes(typeMap: BamlTypeMap) {
typeMap.register("TYPES", "CookingConstraints", baml_client.types.CookingConstraints::class, baml_client.types.CookingConstraints)
    typeMap.register("STREAM_TYPES", "CookingConstraints", baml_client.stream_types.CookingConstraints::class, baml_client.stream_types.CookingConstraints)
typeMap.register("TYPES", "IngredientDetection", baml_client.types.IngredientDetection::class, baml_client.types.IngredientDetection)
    typeMap.register("STREAM_TYPES", "IngredientDetection", baml_client.stream_types.IngredientDetection::class, baml_client.stream_types.IngredientDetection)
typeMap.register("TYPES", "InventoryAnalysis", baml_client.types.InventoryAnalysis::class, baml_client.types.InventoryAnalysis)
    typeMap.register("STREAM_TYPES", "InventoryAnalysis", baml_client.stream_types.InventoryAnalysis::class, baml_client.stream_types.InventoryAnalysis)
typeMap.register("TYPES", "RecipePlan", baml_client.types.RecipePlan::class, baml_client.types.RecipePlan)
    typeMap.register("STREAM_TYPES", "RecipePlan", baml_client.stream_types.RecipePlan::class, baml_client.stream_types.RecipePlan)
typeMap.register("TYPES", "RecipeSuggestion", baml_client.types.RecipeSuggestion::class, baml_client.types.RecipeSuggestion)
    typeMap.register("STREAM_TYPES", "RecipeSuggestion", baml_client.stream_types.RecipeSuggestion::class, baml_client.stream_types.RecipeSuggestion)
typeMap.register("TYPES", "ShoppingItem", baml_client.types.ShoppingItem::class, baml_client.types.ShoppingItem)
    typeMap.register("STREAM_TYPES", "ShoppingItem", baml_client.stream_types.ShoppingItem::class, baml_client.stream_types.ShoppingItem)
typeMap.register("TYPES", "ShoppingPlan", baml_client.types.ShoppingPlan::class, baml_client.types.ShoppingPlan)
    typeMap.register("STREAM_TYPES", "ShoppingPlan", baml_client.stream_types.ShoppingPlan::class, baml_client.stream_types.ShoppingPlan)
typeMap.register("TYPES", "ShoppingPlanDeck", baml_client.types.ShoppingPlanDeck::class, baml_client.types.ShoppingPlanDeck)
    typeMap.register("STREAM_TYPES", "ShoppingPlanDeck", baml_client.stream_types.ShoppingPlanDeck::class, baml_client.stream_types.ShoppingPlanDeck)
typeMap.register("TYPES", "ShoppingPlanOption", baml_client.types.ShoppingPlanOption::class, baml_client.types.ShoppingPlanOption)
    typeMap.register("STREAM_TYPES", "ShoppingPlanOption", baml_client.stream_types.ShoppingPlanOption::class, baml_client.stream_types.ShoppingPlanOption)




}