// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client

import com.boundaryml.baml.*
import baml_client.types.*
import baml_client.stream_types.*
import kotlinx.coroutines.flow.Flow

object BamlStreamFunctions {



    fun AnalyzeFridgeInventoryStream(fridgeImage: baml_client.types.Image, pantryText: String?, userGoal: String?, selectedRestrictions: List<String>, options: CallOptions? = null): Flow<BamlResult> {
        val args = Serde.encodeArgs(mapOf(
            "fridgeImage" to fridgeImage,"pantryText" to pantryText,"userGoal" to userGoal,"selectedRestrictions" to selectedRestrictions
        ), options)
        return BamlRuntime.client.streamFunction("AnalyzeFridgeInventory", args)
    }


    fun BuildShoppingPlanStream(inventory: baml_client.types.InventoryAnalysis, constraints: baml_client.types.CookingConstraints, recipePlan: baml_client.types.RecipePlan, options: CallOptions? = null): Flow<BamlResult> {
        val args = Serde.encodeArgs(mapOf(
            "inventory" to inventory,"constraints" to constraints,"recipePlan" to recipePlan
        ), options)
        return BamlRuntime.client.streamFunction("BuildShoppingPlan", args)
    }


    fun InferCookingConstraintsStream(userGoal: String?, pantryText: String?, selectedRestrictions: List<String>, options: CallOptions? = null): Flow<BamlResult> {
        val args = Serde.encodeArgs(mapOf(
            "userGoal" to userGoal,"pantryText" to pantryText,"selectedRestrictions" to selectedRestrictions
        ), options)
        return BamlRuntime.client.streamFunction("InferCookingConstraints", args)
    }


    fun SuggestRecipePlanStream(inventory: baml_client.types.InventoryAnalysis, constraints: baml_client.types.CookingConstraints, options: CallOptions? = null): Flow<BamlResult> {
        val args = Serde.encodeArgs(mapOf(
            "inventory" to inventory,"constraints" to constraints
        ), options)
        return BamlRuntime.client.streamFunction("SuggestRecipePlan", args)
    }


}