// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client

import com.boundaryml.baml.*
import baml_client.types.*

object BamlParseFunctions {



    /// Parse version of AnalyzeFridgeInventory — takes raw LLM text and returns typed result.
    suspend fun AnalyzeFridgeInventory(text: String, options: CallOptions? = null): baml_client.types.InventoryAnalysis {
        val args = Serde.encodeArgs(mapOf(
            "text" to text,
            "stream" to false
        ), options)
        val result = BamlRuntime.client.callFunctionParse("AnalyzeFridgeInventory", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.InventoryAnalysis
    }


    /// Parse version of BuildShoppingPlan — takes raw LLM text and returns typed result.
    suspend fun BuildShoppingPlan(text: String, options: CallOptions? = null): baml_client.types.ShoppingPlan {
        val args = Serde.encodeArgs(mapOf(
            "text" to text,
            "stream" to false
        ), options)
        val result = BamlRuntime.client.callFunctionParse("BuildShoppingPlan", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.ShoppingPlan
    }


    /// Parse version of InferCookingConstraints — takes raw LLM text and returns typed result.
    suspend fun InferCookingConstraints(text: String, options: CallOptions? = null): baml_client.types.CookingConstraints {
        val args = Serde.encodeArgs(mapOf(
            "text" to text,
            "stream" to false
        ), options)
        val result = BamlRuntime.client.callFunctionParse("InferCookingConstraints", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.CookingConstraints
    }


    /// Parse version of SuggestRecipePlan — takes raw LLM text and returns typed result.
    suspend fun SuggestRecipePlan(text: String, options: CallOptions? = null): baml_client.types.RecipePlan {
        val args = Serde.encodeArgs(mapOf(
            "text" to text,
            "stream" to false
        ), options)
        val result = BamlRuntime.client.callFunctionParse("SuggestRecipePlan", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.RecipePlan
    }


}