// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the BAML Kotlin SDK
//  dependency to your project.
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

package baml_client

import com.boundaryml.baml.*
import baml_client.types.*
import kotlinx.coroutines.flow.Flow

object BamlFunctions {



    suspend fun AnalyzeFridgeInventory(fridgeImage: baml_client.types.Image, pantryText: String?, userGoal: String?, selectedRestrictions: List<String>, options: CallOptions? = null): baml_client.types.InventoryAnalysis {
        val args = Serde.encodeArgs(mapOf(
            "fridgeImage" to fridgeImage,"pantryText" to pantryText,"userGoal" to userGoal,"selectedRestrictions" to selectedRestrictions
        ), options)
        val result = BamlRuntime.client.callFunction("AnalyzeFridgeInventory", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.InventoryAnalysis
    }


    suspend fun BuildShoppingPlans(inventory: baml_client.types.InventoryAnalysis, constraints: baml_client.types.CookingConstraints, recipePlan: baml_client.types.RecipePlan, options: CallOptions? = null): baml_client.types.ShoppingPlanDeck {
        val args = Serde.encodeArgs(mapOf(
            "inventory" to inventory,"constraints" to constraints,"recipePlan" to recipePlan
        ), options)
        val result = BamlRuntime.client.callFunction("BuildShoppingPlans", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.ShoppingPlanDeck
    }


    suspend fun InferCookingConstraints(userGoal: String?, pantryText: String?, selectedRestrictions: List<String>, options: CallOptions? = null): baml_client.types.CookingConstraints {
        val args = Serde.encodeArgs(mapOf(
            "userGoal" to userGoal,"pantryText" to pantryText,"selectedRestrictions" to selectedRestrictions
        ), options)
        val result = BamlRuntime.client.callFunction("InferCookingConstraints", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.CookingConstraints
    }


    suspend fun SuggestRecipePlan(inventory: baml_client.types.InventoryAnalysis, constraints: baml_client.types.CookingConstraints, options: CallOptions? = null): baml_client.types.RecipePlan {
        val args = Serde.encodeArgs(mapOf(
            "inventory" to inventory,"constraints" to constraints
        ), options)
        val result = BamlRuntime.client.callFunction("SuggestRecipePlan", args)
        @Suppress("UNCHECKED_CAST")
        return result as baml_client.types.RecipePlan
    }


}